### ISSUE TITLE
Rebinning histograms related project

### ISSUE THREAD

**Issue by DancingQuanta** [janpipek/physt#24]
Hi I found a project on rebinning histogram at https://github.com/jhykes/rebin and I opened an issue (jhykes/rebin#5) on that project page asking about integrating his code to this project.
I hope you will appreciate it.

**Comment by janpipek** [comment]
Hi. Thanks for the idea. I will have a look at the project. Hopefully, we can find some common ground. Of course, this depends on the compatibility of our approaches and data representation.

**Comment by janpipek** [comment]
Related to #17 (and perhaps #10).

**Comment by janpipek** [comment]
Hi, I have looked at the package. It seems interesting. But on the other hand, it likely serves a complete different goal. Physt does not assume any property of the underlying distribution. This makes it "dumb" but at the same time "precise". So it's up to me (seems it is ;-)) to decide whether to include the functionality, I am going to say no.

Anyway, I can promote it as a link.

**Comment by DancingQuanta** [comment]
Your decision sure, but then you must add a caveat that any underlying
distribution would not be taken into account if you decide to write your
own rebinning or bin merging.

Anyway  rebinning would not be possible without knowing the distribution so
a simple rebin will be based on assumption of uniform distribution.

**Comment by janpipek** [comment]
Sure. I am losing something.

However, I am okay with allowing only trivial rebinnings, i.e. 50 bins into 25, according to a map etc. Even such limited functionality has its uses.

**Comment by DancingQuanta** [comment]
Certainly, every thing have its uses

**Comment by janpipek** [comment]
I left a short notice in the README about the `rebin` project.
