### ISSUE TITLE
Option to center labels on bins

### ISSUE THREAD

**Issue by nzjrs** [janpipek/physt#4]
If you have a large dataset with a small number of values (such as consisting only of integers 1-10) then it would be nice to have the bin x-axis labels at the center under the respective bin instead of at the bin edges.

I recognise this case is more of a 'histogram as bar plot' kind of thing, but it is a use-case I have often.

**Comment by janpipek** [comment]
Seems really like "histogram as bar plot kind of thing", because from the distribution-describing point of view, a bin is always a range (1.0 to 2.0, or 1.5 to 2.5).

Anyway, some approximation of what you mention should be possible (ticks="center" kind of parameter to force this). Or perhaps a generic "category" histogram solution (which I want to include) would be applicable? Let me think about it.

**Comment by nzjrs** [comment]
Understood.

I often have quantized data with few and integer values, but nevertheless want to plot the count of. If the MPL bar plot API was not so terrible then I wouldn't file an issue here ;-)

I would not necessarily consider this as categorical data.

**Comment by janpipek** [comment]
Ok, I included (to support your use case):
- integer binning (bins centered around integers)
- ticks="center" argument for plot method

Example:
```
# Sum of two dice (should be triangle, right?)
dice = np.floor(np.random.rand(10000) * 6) + np.floor(np.random.rand(10000) * 6) + 2
histogram(dice, "integer").plot(ticks="center", density=True);
```

See https://github.com/janpipek/physt/blob/731d0736bb3667d455c348e9d76676df97b8e1aa/doc/Binning.ipynb for the representation :-)

Is that what you wanted?

**Comment by janpipek** [comment]
P.S. Currently supported just for matplotlib. I like bokeh but... later :-)

**Comment by nzjrs** [comment]
Yip, that meets my use-case. Thanks a lot!

FWIW I think supporting two plotting backends is just making extra work for yourself - I think for better or worse MPL is all you need, as ugly as it can be ;-)
