### ISSUE TITLE
please make this library discoverable

### ISSUE THREAD

**Issue by belm0** [janpipek/physt#56]
name:  `physt`  (?)
github tag line:  `P(i/y)thon h(i/y)stograms`   (???)

google search for "python streaming histogram"
  * top result is https://github.com/carsonfarmer/streamhist (unused / unmaintained)
  * physt not in initial 10 pages of results...

For over a year I've wanted to find a Python library which supports efficient histogram updates without a bunch of ugly dependencies.   I've searched many times.  Today I happened to get lucky by seeing physt mentioned at the bottom of a SO question (https://stackoverflow.com/questions/40627274/).

To improve discoverability by search, please consider updating the github tag line to concisely and accurately describe the library (... rather than be cute).

**Comment by janpipek** [comment]
Hi, thanks for the idea.

**Comment by janpipek** [comment]
I changed the description a bit. The name will stay.
