### ISSUE TITLE
Usage of spherical histogram

### ISSUE THREAD

**Issue by zhengpuchen** [janpipek/physt#62]
Hi,
I have tried the example of spherical histogram. After a small modification of the code (normalized the data as unit vectors), 

n = 100
data = np.empty((n, 3))
data[:,0] = np.random.normal(0, 1, n)
data[:,1] = np.random.normal(0, 1, n)
data[:,2] = np.random.normal(0, 1, n)
for i in range(n):
    scale = np.sqrt(data[i,0]**2 + data[i,1]**2 + data[i,2]**2)
    data[i,0] = data[i,0]/scale
    data[i,1] = data[i,1]/scale
    data[i,2] = data[i,2]/scale

h = special.spherical_histogram(data, theta_bins=20, phi_bins=20)
ax.scatter(data[:,0], data[:,1], data[:,2])

globe = h.projection("theta", "phi")
globe.plot.globe_map(density=True, figsize=(7, 7), cmap="rainbow")

plt.show()

I got an error: “RuntimeError: Bins not in rising order.”
What did I do wrong? Thank you for your support.

**Comment by janpipek** [comment]
Hi @zhengpuchen ,

the problem, though not properly reported by the `spherical_histogram` function, is in the range along radial "axis". All radii have the same value (1.0) and numpy (which is used underneath) is not capable to find proper binning. I will alert the user in this case in the future.

What you can do is to use data without scaling. Alternatively, you can use the current `master` that contains an additional function `spherical_surface_histogram` that behaves more or less like spherical + projection. It works but I am still doing some little embellishments to the code before I publish it as 0.4.11.

Hope my explanation is clear :-)

Cheers,
Jan

**Comment by zhengpuchen** [comment]
Thank you for the explanation, Jan!

Another question I have is that for the current spherical histogram the area of the bins is not uniform (the area of the bins near the pole is smaller than the area of the bins near the equator). Would it cause a problem when the probability density function is calculated (like the area calculation near the pole is not very accurate)? Would it possible to make the area of the bins approximately the same (I know that it would not be possible to make them exactly the same)?

Sincerely,

Zhengpu

**Comment by janpipek** [comment]
The area calculation near the pole should be accurate as it is based on analytical computation with sines and cosines. Please, check this if you wish (and let me know!). I hope to write proper test for this as well...

I am afraid creating a variable bin size in theta on the surface of the sphere is a bit beyond the scope of physt but perhaps you could achieve that by providing a custom binning as argument `theta_bins` in `spherical` / `spherical_surface`...
